### ISSUE TITLE
remove `import '@glimmer/env';`

### ISSUE THREAD

**Issue by kellyselden** [chadhietala/babel-plugin-debug-macros#68]
Like https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/38 and https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/39, `import '@glimmer/env';` suffers the same problem and should be removed. It should also be fixed on the 0.1.x series.

**Comment by rwjblue** [comment]
Yep, totally agreed. I only mentioned the options due to curiosity. I have no issue with making sure empty imports from these modules are dropped...
