### ISSUE TITLE
Running ember-server, seeing an error

### ISSUE THREAD

**Issue by xdumaine** [chadhietala/babel-plugin-debug-macros#71]
Started getting this error recently on my project, just when running `ember s` though others don't get it. Any ideas? 

```
The Broccoli Plugin: [Funnel] failed with:
Error: ember-data/-debug/index.js: You must specify envFlags.flags.DEBUG at minimum.
  at normalizeOptions (<redacted>/node_modules/babel-plugin-debug-macros/dist/lib/utils/normalize-options.js:74:11)
  at PluginPass.enter (<redacted>/node_modules/babel-plugin-debug-macros/dist/index.js:33:60)
```

**Comment by xdumaine** [comment]
Realized I had a mixture of yarn and npm going on. Maybe the latest version of this isn't compatible with the version of ember that we're on.

**Comment by buschtoens** [comment]
I'm running into the same issue when trying to run tests for `ember-engines`.

Google also turned this up: https://github.com/ember-learn/ember-cli-addon-docs/issues/292#issuecomment-449770176

**Comment by buschtoens** [comment]
This assertion has been removed. I was able to fix the error in `ember-engines` by upgrading to the latest version of `ember-cli-babel`.
